name: Deploy to EC2

on:
  push:
    branches:
      - Staging  # O cambie 'main' al nombre de su rama a desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@52.45.231.48 cd '/home/ec2-user/treeoma/Treeoma_FrontEnd-1' && sudo git reset --hard && git pull && sudo docker-compose down && sudo docker system prune -a -f && sudo docker-compose build && sudo docker-compose up -d
